import { extractNameFromMultilingual } from './translationHelpers';

// Generates a localized HTML template for an order PDF report
// Accepts { order, user, currentLanguage, t } and returns HTML string
export function generateOrderReportHTML({ order, user, currentLanguage = 'en', t }) {
  if (!order || !user) return '';
  
  const isRTL = currentLanguage === 'ar';
  const logoUrl = 'https://raw.githubusercontent.com/hazemabdo15/Recycling-App/main/assets/images/logo.png';
  const orderDate = new Date(order.createdAt).toLocaleString(currentLanguage === 'ar' ? 'ar-EG' : 'en-US');
  
  // Helper function to get translated item name
  const getItemName = (item) => {
    if (!item) return t ? t('recyclingHistory.unknownItem') : 'Unknown Item';
    
    // Try to get the name from multilingual structure first
    const itemName = item.itemName || item.name;
    if (itemName && typeof itemName === 'object') {
      return extractNameFromMultilingual(itemName, currentLanguage);
    }
    
    // Fallback to string name
    return itemName || (t ? t('recyclingHistory.unknownItem') : 'Unknown Item');
  };
  
  // Helper function to get translated status
  const getTranslatedStatus = (status) => {
    if (!t) return status;
    return t(`recyclingHistory.orderStatus.${status}`) || status;
  };
  
  const itemsRows = order.items.map(
    (item, idx) => `
      <tr>
        <td>${idx + 1}</td>
        <td style="text-align: ${isRTL ? 'right' : 'left'};">${getItemName(item)}</td>
        <td>${item.quantity} ${item.measurement_unit === 1 ? (t ? t('units.kg') : 'kg') : (t ? t('units.pieces') : 'pcs')}</td>
        <td>${item.points || '-'}</td>
        <td>${item.price || '-'} ${t ? t('units.egp') : 'EGP'}</td>
      </tr>`
  ).join('');
  
  const addressText = `${order.address?.street || ''}, ${t ? t('recyclingHistory.pdfReport.building') : 'Bldg'} ${order.address?.building || ''}, ${t ? t('recyclingHistory.pdfReport.floor') : 'Floor'} ${order.address?.floor || ''}, ${order.address?.area || ''}, ${order.address?.city || ''}`;
  
  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { 
          font-family: ${isRTL ? 'Arial, "Segoe UI", Tahoma, sans-serif' : 'Arial, sans-serif'}; 
          color: #111; 
          background: #fff; 
          direction: ${isRTL ? 'rtl' : 'ltr'};
        }
        .header { text-align: center; margin-bottom: 24px; }
        .logo { height: 60px; margin-bottom: 8px; }
        .title { font-size: 22px; font-weight: bold; margin-bottom: 4px; }
        .subtitle { font-size: 14px; color: #555; margin-bottom: 16px; }
        .section { margin-bottom: 18px; }
        .section-title { font-weight: bold; font-size: 15px; margin-bottom: 6px; }
        table { 
          width: 100%; 
          border-collapse: collapse; 
          margin-top: 8px;
          direction: ${isRTL ? 'rtl' : 'ltr'};
        }
        th, td { 
          border: 1px solid #222; 
          padding: 6px 8px; 
          font-size: 13px;
          text-align: ${isRTL ? 'right' : 'left'};
        }
        th { background: #f3f3f3; }
        tfoot td { font-weight: bold; }
        .footer { margin-top: 32px; font-size: 12px; color: #888; text-align: center; }
        .info-line { margin-bottom: 4px; }
      </style>
    </head>
    <body>
      <div class="header">
        <img src="${logoUrl}" class="logo" alt="App Logo" />
        <div class="title">${t ? t('recyclingHistory.pdfReport.title') : 'Order Report'}</div>
        <div class="subtitle">${t ? t('recyclingHistory.pdfReport.subtitle') : 'Generated by Karakeeb App'}</div>
      </div>
      <div class="section">
        <div class="section-title">${t ? t('recyclingHistory.pdfReport.userInformation') : 'User Information'}</div>
        <div class="info-line">${t ? t('recyclingHistory.pdfReport.name') : 'Name'}: ${user.name || user.userName || '-'}</div>
        <div class="info-line">${t ? t('recyclingHistory.pdfReport.email') : 'Email'}: ${user.email || '-'}</div>
        <div class="info-line">${t ? t('recyclingHistory.pdfReport.phone') : 'Phone'}: ${user.phoneNumber || '-'}</div>
      </div>
      <div class="section">
        <div class="section-title">${t ? t('recyclingHistory.pdfReport.orderInformation') : 'Order Information'}</div>
        <div class="info-line">${t ? t('recyclingHistory.pdfReport.orderId') : 'Order ID'}: ${order._id}</div>
        <div class="info-line">${t ? t('recyclingHistory.pdfReport.date') : 'Date'}: ${orderDate}</div>
        <div class="info-line">${t ? t('recyclingHistory.pdfReport.status') : 'Status'}: ${getTranslatedStatus(order.status)}</div>
        <div class="info-line">${t ? t('recyclingHistory.pdfReport.address') : 'Address'}: ${addressText}</div>
      </div>
      <div class="section">
        <div class="section-title">${t ? t('recyclingHistory.pdfReport.orderItems') : 'Order Items'}</div>
        <table>
          <thead>
            <tr>
              <th>${t ? t('recyclingHistory.pdfReport.itemNumber') : '#'}</th>
              <th>${t ? t('recyclingHistory.pdfReport.item') : 'Item'}</th>
              <th>${t ? t('recyclingHistory.pdfReport.quantity') : 'Quantity'}</th>
              <th>${t ? t('recyclingHistory.pdfReport.points') : 'Points'}</th>
              <th>${t ? t('recyclingHistory.pdfReport.price') : 'Price'}</th>
            </tr>
          </thead>
          <tbody>
            ${itemsRows}
          </tbody>
        </table>
      </div>
      <div class="footer">
        ${t ? t('recyclingHistory.pdfReport.footer') : 'Karakeeb App © 2025 | Contact: recyclecrew7@gmail.com'}
      </div>
    </body>
  </html>
  `;
}
