// Generates a black-and-white HTML template for an order PDF report
// Accepts { order, user } and returns HTML string
export function generateOrderReportHTML({ order, user }) {
  if (!order || !user) return '';
  const logoUrl = 'https://raw.githubusercontent.com/hazemabdo15/Recycling-App/main/assets/images/logo.png'; // fallback logo
  const orderDate = new Date(order.createdAt).toLocaleString();
  const itemsRows = order.items.map(
    (item, idx) => `
      <tr>
        <td>${idx + 1}</td>
        <td>${item.itemName || ''}</td>
        <td>${item.quantity} ${item.measurement_unit === 1 ? 'kg' : 'pcs'}</td>
        <td>${item.points || '-'}</td>
        <td>${item.price || '-'} EGP</td>
      </tr>`
  ).join('');
  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: Arial, sans-serif; color: #111; background: #fff; }
        .header { text-align: center; margin-bottom: 24px; }
        .logo { height: 60px; margin-bottom: 8px; }
        .title { font-size: 22px; font-weight: bold; margin-bottom: 4px; }
        .subtitle { font-size: 14px; color: #555; margin-bottom: 16px; }
        .section { margin-bottom: 18px; }
        .section-title { font-weight: bold; font-size: 15px; margin-bottom: 6px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #222; padding: 6px 8px; font-size: 13px; }
        th { background: #f3f3f3; }
        tfoot td { font-weight: bold; }
        .footer { margin-top: 32px; font-size: 12px; color: #888; text-align: center; }
      </style>
    </head>
    <body>
      <div class="header">
        <img src="${logoUrl}" class="logo" alt="App Logo" />
        <div class="title">Order Report</div>
        <div class="subtitle">Generated by Recycling App</div>
      </div>
      <div class="section">
        <div class="section-title">User Information</div>
        <div>Name: ${user.name || user.userName || '-'}</div>
        <div>Email: ${user.email || '-'}</div>
        <div>Phone: ${user.phoneNumber || '-'}</div>
      </div>
      <div class="section">
        <div class="section-title">Order Information</div>
        <div>Order ID: ${order._id}</div>
        <div>Date: ${orderDate}</div>
        <div>Status: ${order.status}</div>
        <div>Address: ${order.address?.street || ''}, Bldg ${order.address?.building || ''}, Floor ${order.address?.floor || ''}, ${order.address?.area || ''}, ${order.address?.city || ''}</div>
      </div>
      <div class="section">
        <div class="section-title">Order Items</div>
        <table>
          <thead>
            <tr><th>#</th><th>Item</th><th>Quantity</th><th>Points</th><th>Price</th></tr>
          </thead>
          <tbody>
            ${itemsRows}
          </tbody>
        </table>
      </div>
      <div class="footer">
        Recycling App &copy; 2025 | Contact: support@recyclingapp.com
      </div>
    </body>
  </html>
  `;
}
